# This is a basic workflow to help you get started with Actions
name: Deploy on dev branch update

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run hello script
      run: |
        chmod +x Hello.sh
        ./Hello.sh

    - name: Merge dev into main
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git merge dev --no-ff --no-edit
          git push
