name: merge
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Git fetch
        run: git fetch
      - name: Run Hello script
        run: |
          chmod +x Hello.sh
          ./Hello.sh 
      - name: checkout main
        run: git checkout main
      - name: config
        run: |
          git config --global user.email "2507836311@qq.com"
          git config --global user.name "kksk114"
      - name: merge dev
        run: git merge --no-ff --allow-unrelated-histories dev
      - name: git push
        run: git push origin main
